<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>POS.UI</RootNamespace>
    <AssemblyName>PuntoDeVenta</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\Logo_Empresa.jpeg" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\POS.Core\POS.Core.csproj" />
    <ProjectReference Include="..\POS.Data\POS.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Logo_Empresa.jpeg" />
  </ItemGroup>

</Project>
